version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  app:
    build: .
    container_name: nextjs-app
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://${MONGODB_USERNAME}:${MONGODB_USERNAME}@mongodb:27017"
